/* Auto-generated by tools/sync-music-catalog.mjs. */
export const MUSIC_TRACKS = [
  {key:"country-jd-souther-you-re-only-lonely",genre:"country",genreLabel:"COUNTRY",label:"You're Only Lonely",artist:"JD Souther",file:"music/active/country/JD Souther - You're Only Lonely.mp3"},
  {key:"country-open-road",genre:"country",genreLabel:"COUNTRY",label:"Open Road",artist:"",file:"music/active/country/open-road.wav"},
  {key:"country-sunset-rally",genre:"country",genreLabel:"COUNTRY",label:"Sunset Rally",artist:"",file:"music/active/country/sunset-rally.wav"},
  {key:"disco-boney-m-rasputin",genre:"disco",genreLabel:"DISCO",label:"Rasputin",artist:"Boney M",file:"music/active/disco/Boney M - Rasputin.mp3"},
  {key:"kpop-neon-spark",genre:"kpop",genreLabel:"KPOP",label:"Neon Spark",artist:"",file:"music/active/kpop/neon-spark.wav"},
  {key:"kpop-seoul-rush",genre:"kpop",genreLabel:"KPOP",label:"Seoul Rush",artist:"",file:"music/active/kpop/seoul-rush.wav"},
  {key:"pop-a-ha-take-on-me",genre:"pop",genreLabel:"POP",label:"Take On Me",artist:"A-ha",file:"music/active/pop/A-ha - Take On Me.mp3"},
  {key:"pop-rick-astley-never-gonna-give-you-up",genre:"pop",genreLabel:"POP",label:"Never Gonna Give You Up",artist:"Rick Astley",file:"music/active/pop/Rick Astley - Never Gonna Give You Up.mp3"},
  {key:"pop-match-lights",genre:"pop",genreLabel:"POP",label:"Match Lights",artist:"",file:"music/active/pop/match-lights.wav"},
  {key:"pop-skyline-set",genre:"pop",genreLabel:"POP",label:"Skyline Set",artist:"",file:"music/active/pop/skyline-set.wav"},
  {key:"rap-dr-dre-still-dre",genre:"rap",genreLabel:"RAP",label:"Still Dre",artist:"Dr Dre",file:"music/active/rap/Dr Dre - Still Dre.mp3"},
  {key:"rap-baseline",genre:"rap",genreLabel:"RAP",label:"Baseline",artist:"",file:"music/active/rap/baseline.wav"},
  {key:"rap-locker-room",genre:"rap",genreLabel:"RAP",label:"Locker Room",artist:"",file:"music/active/rap/locker-room.wav"},
  {key:"rock-acdc-thunderstruck",genre:"rock",genreLabel:"ROCK",label:"Thunderstruck",artist:"ACDC",file:"music/active/rock/ACDC - Thunderstruck.mp3"},
  {key:"rock-radiohead-creep",genre:"rock",genreLabel:"ROCK",label:"Creep",artist:"Radiohead",file:"music/active/rock/Radiohead - Creep.mp3"},
];
